import type { StorageBackend } from '@dastan/plugin-api';
import {
	createDocument,
	createEmptyDocumentContent,
	createProject,
	deleteProject,
	getActiveDocuments,
	getAllDocuments,
	getAllProjects,
	getProjectById,
	getTrashedDocuments,
	getVersionHistory,
	loadDocumentById,
	loadLastDocument,
	moveDocumentToProject,
	permanentlyDeleteDocument,
	purgeExpiredTrash,
	renameDocument,
	renameProject,
	restoreDocument,
	restoreVersionSnapshot,
	saveDocument,
	saveVersionSnapshot,
	saveVersion,
	setLastDocumentId,
	softDeleteDocument,
	createManualVersionSnapshot,
	updateProject,
	saveProject,
	duplicateDocument,
	duplicateProject,
	getTrashedProjects,
	restoreProject,
	permanentlyDeleteProject,
} from '@dastan/local-storage';

export const localStorageBackend: StorageBackend = {
	documents: {
		get: loadDocumentById,
		save: saveDocument,
		list: getAllDocuments,
		listActive: getActiveDocuments,
		listTrashed: getTrashedDocuments,
		create: createDocument,
		rename: renameDocument,
		softDelete: softDeleteDocument,
		restore: restoreDocument,
		permanentlyDelete: permanentlyDeleteDocument,
		moveToProject: moveDocumentToProject,
		duplicate: duplicateDocument,
		loadLast: loadLastDocument,
		setLastDocumentId,
		createEmptyContent: createEmptyDocumentContent,
		purgeExpiredTrash,
	},
	projects: {
		list: getAllProjects,
		get: getProjectById,
		save: saveProject,
		create: createProject,
		rename: renameProject,
		update: updateProject,
		delete: deleteProject,
		duplicate: duplicateProject,
		listTrashed: getTrashedProjects,
		restore: restoreProject,
		permanentlyDelete: permanentlyDeleteProject,
	},
	versions: {
		saveSnapshot: saveVersionSnapshot,
		save: saveVersion,
		createManualSnapshot: createManualVersionSnapshot,
		list: getVersionHistory,
		restore: restoreVersionSnapshot,
	},
};
